version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - ./images:/app/images  

  db:
    image: mysql:8
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
